### ISSUE TITLE
主页左上角的粉色Hexo，怎么更换？

### ISSUE THREAD

**Issue by kay6666** [jiehua1995/hexo-theme-love#1]
找了好久文件看了好多，也没找到在哪里改，我需要帮助，感谢

**Comment by kay6666** [comment]
倒是可以在html里改，不过每次hexo d之后，就还原成hexo了。我还比较菜，正在学习中。

**Comment by kay6666** [comment]
已经解决了。谢谢

**Comment by jiehua1995** [comment]
不好意思，我这几个月都在忙课题，没来得及上github。能自己解决很好呀~
是在这里修改的吗？
![image](https://user-images.githubusercontent.com/31189087/89927189-853f0300-dc38-11ea-9e99-027edfc7bf6c.png)

**Comment by jiehua1995** [comment]
最近准备新做一个版本，也许会添加自定义颜色 功能
