### ISSUE TITLE
自定义壁纸& 自定义语句

### ISSUE THREAD

**Issue by zhuoshuai** [jiehua1995/hexo-theme-love#4]
1. 壁纸功能： 我自己试了加入添加「background-image」，不过屏幕适配像是平铺的一样，不太好；
2. 语句：boy 和 girl 的属性是放在「date 」里， 颜色和「date 」的颜色一样是粉红，不能单独控制，可以把「语句」整句话放在配置文件里，并加入 RGB  颜色&对齐方式的配置；

**Comment by jiehua1995** [comment]
> 1. 壁纸功能： 我自己试了加入添加「background-image」，不过屏幕适配像是平铺的一样，不太好；
> 2. 语句：boy 和 girl 的属性是放在「date 」里， 颜色和「date 」的颜色一样是粉红，不能单独控制，可以把「语句」整句话放在配置文件里，并加入 RGB  颜色&对齐方式的配置；

1. 壁纸：这个可以自己修改下CSS，按照自己想要的方式设定就好。
2. 这个主题主要是给小白用的，所以越简单越好。如果你想要的话，可以让他们变成<a>,给个标记，然后去css定义它的颜色之类的。

**Comment by jiehua1995** [comment]
1. 关于壁纸，我想给你推荐一个库：https://github.com/jquery-backstretch/jquery-backstretch
借助这个库，可以方便的实现背景图片适应或者轮播。
3. 关于自定义语句，之后可以考虑改一下。
