### ISSUE TITLE
希望可以增加友链页

### ISSUE THREAD

**Issue by TRHX** [jiehua1995/hexo-theme-love#7]
希望可以增加友链页，简单一点即可

**Comment by TRHX** [comment]
还有一个就是网页底部的版权、备案信息之类的

**Comment by jiehua1995** [comment]
> 还有一个就是网页底部的版权、备案信息之类的

抱歉，版权、备案信息等其他功能会破坏页面的简洁性，如果你需要的话可以自己在layout.ejs里面添加你需要的信息。
友链页似乎没什么用，对于此主题而言。如果你有需要可以自行添加page及相关布局。
其实我一直觉得这个页面适合放到一个简单的废旧平板或者手机，放在家里。
